#!/usr/bin/env sh

HERE="$(dirname "$(readlink -f "$0")")"

# export LD_LIBRARY_PATH="${HERE}/usr/lib/x86_64-linux-gnu:${HERE}/usr/lib"

# export GIO_MODULE_DIR="${HERE}/usr/lib/x86_64-linux-gnu/gio/modules"

# export PYTHONPATH="${HERE}/usr/local/lib/python3.9/site-packages"

# export GTK_THEME="Adwaita-dark"
# export GTK_PATH="${HERE}/usr/lib/x86_64-linux-gnu/gtk-3.0"
# export XDG_DATA_DIRS="${HERE}/usr/share:${XDG_DATA_DIRS}"

# export QT_PLUGIN_PATH="${HERE}/usr/lib/x86_64-linux-gnu/qt6/plugins"
# export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms"
# export QML2_IMPORT_PATH="${HERE}/usr/lib/x86_64-linux-gnu/qt6/qml"

# "${HERE}/usr/local/bin/python3.9" "${HERE}/usr/local/share/nut/nut_gui.py" "$@"

exec "${HERE}/sharun" python3 nut_gui.py "$@"
