name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          VERSION="$(python3 -c "import runpy; print(runpy.run_path('__version__.py')['__version__'])")"
          docker build \
            --file AppImage.Dockerfile \
            --tag blawar_nut-appimage \
            --build-arg VERSION="${VERSION}" \
            .

      - name: Extract assets
        run: |
          container_id=$(docker create blawar_nut-appimage)
          docker cp "${container_id}":/out ./out
          docker rm "${container_id}"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files:
            ./out/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
