name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          VERSION="$(python3 -c "from nut.__version__ import __version__; print(__version__)")"
          docker build \
            --file AppImage.Dockerfile \
            --tag blawar_nut-AppImage \
            --build-arg VERSION="${VERSION}"
            .

      - name: Extract artifacts
        run: |
          container_id=$(docker create blawar_nut-AppImage)
          docker cp "${container_id}":/out ./out
          docker rm "${container_id}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: ./out
