name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t nut .

      - name: Extract artifacts
        run: |
          container_id=$(docker create nut)
          docker cp "$container_id":/out ./out
          docker rm "$container_id"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: ./out
